//! F4 node-DB compatibility fixture (part 01-storage, plan § Part-specific notes).
//!
//! `node-v1.sqlite` is a genuine Node/better-sqlite3-created `vibe-station.db`
//! at migration head (schema version 1), generated by running the TS
//! `ensureSchema` verbatim. This test verifies the Rust migration runner opens
//! it as a no-op and produces an identical schema.

use rusqlite::Connection;
use vst_store::schema::ensure_schema;

fn fixture_dir() -> std::path::PathBuf {
    let dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/db");
    assert!(dir.exists(), "fixture dir missing: {}", dir.display());
    dir
}

/// Dump `.schema` the same way the fixture generator did (tables+indexes,
/// ordered by name) so the comparison is deterministic.
fn dump_schema(conn: &Connection) -> String {
    let mut stmt = conn
        .prepare(
            "SELECT sql FROM sqlite_master WHERE sql IS NOT NULL AND type IN ('table','index') ORDER BY name",
        )
        .unwrap();
    let mut out = String::new();
    let rows = stmt
        .query_map([], |r| r.get::<_, String>(0))
        .unwrap()
        .collect::<Result<Vec<_>, _>>()
        .unwrap();
    for sql in rows {
        out.push_str(&sql);
        out.push_str(";\n");
    }
    out
}

#[test]
fn rust_open_of_node_db_is_a_schema_noop() {
    let dir = fixture_dir();
    let node_db = dir.join("node-v1.sqlite");
    assert!(node_db.exists(), "node fixture missing");

    // The committed schema dump — the ground truth for F4.
    let expected = std::fs::read_to_string(dir.join("schema-dump.sql")).unwrap();

    let conn = Connection::open(&node_db).unwrap();
    // The migration runner's open pass must be a no-op: no error, no schema drift.
    ensure_schema(&conn).unwrap();

    let actual = dump_schema(&conn);
    assert_eq!(
        actual, expected,
        "Rust schema diverged from Node-created schema"
    );
}

#[test]
fn node_db_opens_and_can_be_written_to() {
    // Ensures the fixture isn't just readable — the store can actually operate
    // on a Node-created database (F4's "readable across the transition").
    let dir = fixture_dir();
    let tmp = tempfile::tempdir().unwrap();
    let copy = tmp.path().join("copy.sqlite");
    std::fs::copy(dir.join("node-v1.sqlite"), &copy).unwrap();

    let conn = Connection::open(&copy).unwrap();
    conn.execute(
        "INSERT INTO projects (id, absolutePath, prefix, isGit, createdAt) VALUES ('p1', '/p1', 'p', 1, '2024-01-01T00:00:00Z')",
        [],
    )
    .unwrap();
    let n: i64 = conn
        .query_row("SELECT COUNT(*) FROM projects WHERE id='p1'", [], |r| {
            r.get(0)
        })
        .unwrap();
    assert_eq!(n, 1);
}
